# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_is_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
            ],
            options={
                'verbose_name': 'Blood Center',
                'verbose_name_plural': 'Blood Centers',
            },
        ),
    ]
