# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('description', models.TextField(verbose_name='Description')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('status', models.CharField(choices=[('Urgent', 'Urgent'), ('Closed', 'Closed'), ('Expired', 'Expired')], max_length=20, verbose_name='Status')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
        ),
    ]
