# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=1024, verbose_name='Street')),
                ('city', models.CharField(max_length=64, verbose_name='City')),
                ('country', models.CharField(max_length=64, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Zip code')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone number')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('blood_type', models.CharField(choices=[('O-', 'O-'), ('O+', 'O+'), ('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+')], max_length=10, verbose_name='Blood type')),
                ('email_notification', models.BooleanField(default=False, verbose_name='Email notification')),
                ('sms_notification', models.BooleanField(default=False, verbose_name='SMS notification')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
