"""
Django settings for blood_donation_platform project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

from . import credentials

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'eijfuluy1g=q8fd1x@9w8+$m$*6iqfz3h^5!v#_&a4z%1$(s@5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django sites framework
    # https://docs.djangoproject.com/en/1.11/ref/contrib/sites/#enabling-the-sites-framework
    'django.contrib.sites',

    #Third party apps
    # django rest framework
    'rest_framework',
    # DRF JWT token
    'rest_framework_jwt',
    # django swagger
    'rest_framework_swagger',

    # my developped apps
    'accounts.apps.AccountsConfig',
    'donations.apps.DonationsConfig',
    'posts.apps.PostsConfig',
    'comments.apps.CommentsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # My middlewares :
    'accounts.api.middlewares.JWTTokenMiddleware',
]

ROOT_URLCONF = 'blood_donation_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blood_donation_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


# The model to use to represent a User. (Default: 'auth.User')

AUTH_USER_MODEL = 'accounts.User'


# My Site ID for django Sites Framework
# See https://docs.djangoproject.com/en/1.11/ref/contrib/sites/#enabling-the-sites-framework

SITE_ID = 1

# Email Settings
# see https://docs.djangoproject.com/en/1.11/topics/email/#configuring-email-for-development

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'angular.blood.donation@gmail.com'
EMAIL_HOST_PASSWORD = credentials.EMAIL_PASSWORD
EMAIL_PORT = 587
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'From_Younes@gmail.com'


# Cache Settings
# see https://docs.djangoproject.com/en/1.11/topics/cache/
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': 60*30,
    }
}


#####################################################################################################################
#################################  THIRD PARTY PACKAGES RELATED SETTINGS  ###########################################
#####################################################################################################################

# REST framework settings
REST_FRAMEWORK = {

    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    #     'rest_framework.permissions.IsAdminUser',
    # ),

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ),

    'DEFAULT_PARSER_CLASSES': (
        'rest_camel_case.parsers.CamelCaseJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),

    'DEFAULT_RENDERER_CLASSES': (
        'rest_camel_case.renderers.CamelCaseJSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

}

# JWT Token settings :
JWT_AUTH = {
    # By default :  'JWT_AUTH_HEADER_PREFIX' : 'JWT',
    # By default : 'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    'JWT_ALLOW_REFRESH': True,
    # By default : 'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization'
        }
    },
    'LOGIN_URL' : 'rest_framework:login',
    'LOGOUT_URL' : 'rest_framework:logout',
    'JSON_EDITOR' : False,
    'SHOW_REQUEST_HEADERS' : False,

}

# Twilio API SMS
TWILIO_ACCOUNT_SID = credentials.TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN = credentials.TWILIO_AUTH_TOKEN
TWILIO_PHONE_NUMBER = credentials.TWILIO_PHONE_NUMBER

#Client relative routes
ACCOUNT_ACTIVATION_ROUTE = "users/activate"
PASSWORD_RESET_ROUTE = "users/reset-password/reset"

#Pagination Settings
DONATION_LIST_PAGE_SIZE = 5